//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_Project
{


    public partial class MyAttendance
    {
        protected global::System.Web.UI.WebControls.Label lblDateBadge;
        protected global::System.Web.UI.WebControls.GridView gvAttendance;
    }
}
