//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_Project
{


    public partial class MyLateAbsence
    {
        protected global::System.Web.UI.WebControls.Label lblLateCount;
        protected global::System.Web.UI.WebControls.Label lblAbsenceCount;
        protected global::System.Web.UI.WebControls.Label lblPaidLeaveUsed;
        protected global::System.Web.UI.WebControls.Panel pnlPaidBar;
        protected global::System.Web.UI.WebControls.Button btnApplyLeave;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlLeaveForm;
        protected global::System.Web.UI.WebControls.TextBox txtLeaveDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlLeaveType;
        protected global::System.Web.UI.WebControls.TextBox txtLeaveReason;
        protected global::System.Web.UI.WebControls.Button btnSubmitLeave;
        protected global::System.Web.UI.WebControls.Button btnCancelLeave;
        protected global::System.Web.UI.WebControls.Panel pnlEditReason;
        protected global::System.Web.UI.WebControls.HiddenField hdnEditRecordID;
        protected global::System.Web.UI.WebControls.TextBox txtLateReason;
        protected global::System.Web.UI.WebControls.Button btnSaveReason;
        protected global::System.Web.UI.WebControls.Button btnCancelReason;
        protected global::System.Web.UI.WebControls.GridView gvRecords;
    }
}
