//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_Project
{


    public partial class StaffDashboard
    {
        protected global::System.Web.UI.WebControls.Label lblWelcomeName;
        protected global::System.Web.UI.WebControls.Label lblTodayDate;
        protected global::System.Web.UI.WebControls.Label lblClockStatus;
        protected global::System.Web.UI.WebControls.Label lblClockSince;
        protected global::System.Web.UI.WebControls.Button btnClockIn;
        protected global::System.Web.UI.WebControls.Button btnClockOut;
        protected global::System.Web.UI.WebControls.Label lblDaysPresent;
        protected global::System.Web.UI.WebControls.Label lblPendingOT;
        protected global::System.Web.UI.WebControls.Label lblPaidLeave;
    }
}
