//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_Project.Admin
{


    public partial class AdminDashboard
    {
        protected global::System.Web.UI.WebControls.Label lblTodayDate;
        protected global::System.Web.UI.WebControls.Label lblTotalStaff;
        protected global::System.Web.UI.WebControls.Label lblNewThisQuarter;
        protected global::System.Web.UI.WebControls.Label lblPresentToday;
        protected global::System.Web.UI.WebControls.Label lblAttendancePct;
        protected global::System.Web.UI.WebControls.Label lblOTPending;
        protected global::System.Web.UI.WebControls.Label lblLateAbsent;
        protected global::System.Web.UI.WebControls.Label lblLateAbsentDetail;
        protected global::System.Web.UI.WebControls.Label lblAvgAttendance;
        protected global::System.Web.UI.WebControls.Label lblAvgOT;
    }
}
