//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_Project.Admin
{
    public partial class AdminAttendance
    {
        protected global::System.Web.UI.WebControls.Label lblTodayDate;
        protected global::System.Web.UI.WebControls.Label lblPresentCount;
        protected global::System.Web.UI.WebControls.Label lblLateCount;
        protected global::System.Web.UI.WebControls.Label lblAbsentCount;
        protected global::System.Web.UI.WebControls.GridView gvAttendance;
    }
}
