//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_Project.Admin
{


    public partial class AdminLateAbsence
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblLateCount;
        protected global::System.Web.UI.WebControls.Label lblAbsenceCount;
        protected global::System.Web.UI.WebControls.Label lblPendingCount;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilter;
        protected global::System.Web.UI.WebControls.GridView gvRecords;
    }
}
