//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_Project.Admin
{
    public partial class AdminStaffProfile
    {
        protected global::System.Web.UI.WebControls.Label lblCount;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.GridView gvStaff;
        protected global::System.Web.UI.WebControls.HiddenField hdnDeleteId;
        protected global::System.Web.UI.WebControls.Button btnConfirmDelete;
    }
}
